#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")" || exit
LOGGING_PREFIX='\033[90m[\033[33mCoolCLK\033[90m/\033[36mturn-live-photos\033[90m] \033[0m'

check_python() {
    if ! command -v python3 &>/dev/null; then
        echo "${LOGGING_PREFIX}错误：未找到Python"
        exit 1
    fi

    PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
    if [[ "$PYTHON_VERSION" != "$PYTHON_RECOMMENDED_VERSION" ]]; then
        echo "${LOGGING_PREFIX}警告：您正在使用不受支持的Python版本 $PYTHON_VERSION"
        echo "${LOGGING_PREFIX}推荐使用 Python $PYTHON_RECOMMENDED_VERSION"
    fi
}

create_venv() {
    if [[ ! -d "$VENV_HOME" ]]; then
        echo "${LOGGING_PREFIX}正在创建虚拟环境..."
        python3 -m venv "$VENV_HOME"
        echo "${LOGGING_PREFIX}在 $VENV_HOME 创建了虚拟环境"
    fi
    source "$VENV_HOME/bin/activate"
    echo "${LOGGING_PREFIX}已激活虚拟环境"
}

check_dependencies() {
    read -p "${LOGGING_PREFIX}是否检查依赖 (Y/n) " -n 1 -r
    echo
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
        echo -ne "${LOGGING_PREFIX}\033[31m正在安装依赖...\033[0m\n"
        pip3 install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple >/dev/null 2>&1
        pip3 install torch==2.7.0+cu128 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128 >/dev/null 2>&1
        pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple >/dev/null 2>&1
    fi
}

download_model() {
    read -p "${LOGGING_PREFIX}是否下载/更新模型 (Y/n) " -n 1 -r
    echo
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
        if ! command -v git &>/dev/null; then
            echo "${LOGGING_PREFIX}未找到Git，跳过模型下载"
            return
        fi

        MODEL_URL="https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt"
        read -p "${LOGGING_PREFIX}是否使用hf-mirror.com镜像 (Y/n) " -n 1 -r
        echo
        if [[ "$REPLY" =~ ^[Yy]$ ]]; then
            MODEL_URL="https://hf-mirror.com/stabilityai/stable-video-diffusion-img2vid-xt"
        fi

        if [[ -d "$MODELS_HOME/stabilityai/stable-video-diffusion-img2vid-xt" ]]; then
            MODEL_ACTION="pull"
        else
            mkdir -p "$MODELS_HOME/stabilityai"
            MODEL_ACTION="clone"
        fi

        echo -ne "${LOGGING_PREFIX}\033[31m正在拉取模型...\033[0m\n"
        (cd "$MODELS_HOME/stabilityai" && \
         git lfs install >/dev/null 2>&1 && \
         git $MODEL_ACTION $MODEL_URL)
    fi
}

main() {
    echo "${LOGGING_PREFIX}启动Python脚本"
    "$VENV_HOME/bin/python" __main__.py
    echo "${LOGGING_PREFIX}Python脚本已停止"
}

cleanup() {
    echo "${LOGGING_PREFIX}停用虚拟环境"
    deactivate
}

readonly VENV_HOME=".venv"
readonly PYTHON_HOME="$VENV_HOME/bin"
readonly PYTHON_RECOMMENDED_VERSION="3.10.6"
readonly MODELS_HOME="./models"

check_python
create_venv
check_dependencies
download_model
main
cleanup